server:
  port: 8082
  shutdown: graceful

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-batch
  profiles:
    active: local
  
  datasource:
    url: jdbc:mysql://localhost:3306/commerce_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

loopers:
  kafka:
    topics:





---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false